=== rouabas/projectarchiver/ProjectArchiver/war/xml/listeDesCours.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listeDesCours">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="cours">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1">
                            <xs:element name="nom" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rouabas/projectarchiver/ProjectArchiver/war/xml/listeDesCours.xml
<?xml version="1.0" encoding="UTF-8"?>
<listeDesCours xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="listeDesCours.xsd">
  <cours id="1">
    <nom>BDR</nom>
  </cours>
  <cours id="2">
    <nom>XML</nom>
  </cours>
  <cours id="3">
    <nom>WEB</nom>
  </cours>
  <cours id="4">
    <nom>GEN</nom>
  </cours>
  <cours id="5">
    <nom>PDG</nom>
  </cours>
</listeDesCours>
