=== rouabas/projectarchiver/trunk/ProjectArchiver/war/xml/projets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="projets">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="projet">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="titre" type="xs:string"/>
                            <xs:element name="idBranche" type="xs:integer"/>
                            <xs:element name="synopsis" type="xs:string"/>
                            <xs:element name="ajouteLe" type="xs:date"/>
                            <xs:element name="responsables">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="responsable" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="auteurs">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="auteur" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="motsCle">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="motCle" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nomArchive" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rouabas/projectarchiver/ProjectArchiver/war/xml/projets.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="projets.xsl"?>
<projets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projets.xsd">
  <projet id="1">
    <titre>Test</titre>
    <idBranche>2</idBranche>
    <synopsis>Super résumé</synopsis>
    <ajouteLe>05/06/2009</ajouteLe>
    <responsables>
      <responsable>greg</responsable>
    </responsables>
    <auteurs>
      <auteur>super</auteur>
    </auteurs>
    <motsCle>
      <motCle>albert</motCle>
    </motsCle>
    <nomArchive>TODO.rtf</nomArchive>
  </projet>
  <projet id="2">
    <titre>That\'s the way</titre>
    <idBranche>2</idBranche>
    <synopsis>fdsafads</synopsis>
    <ajouteLe>05/06/2009</ajouteLe>
    <responsables>
      <responsable>Super</responsable>
    </responsables>
    <auteurs>
      <auteur>Cool</auteur>
    </auteurs>
    <motsCle>
      <motCle>Francis</motCle>
    </motsCle>
    <nomArchive>GestionProjet.php</nomArchive>
  </projet>
</projets>

=== rouabas/projectarchiver/trunk/ProjectArchiver/war/xml/projets.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="projets.xsl"?>
<projets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projets.xsd">
  <projet id="1">
    <titre>Project Archiver</titre>
    <idBranche>3</idBranche>
    <synopsis>Ce projet permet d\'archiver les projets réalisés à la HEIG-VD.</synopsis>
    <ajouteLe>02/06/2009</ajouteLe>
    <responsables>
      <responsable>Eric Lefrançois</responsable>
    </responsables>
    <auteurs>
      <auteur>Grégory Brissonnette</auteur>
      <auteur>Thomas Jordan</auteur>
      <auteur>Grégory Moinat</auteur>
    </auteurs>
    <motsCle>
      <motCle>XML</motCle>
      <motCle>GWT</motCle>
      <motCle>XPATH</motCle>
      <motCle>XSLT</motCle>
    </motsCle>
    <nomArchive>Project Archiver Rapport.rtf</nomArchive>
  </projet>
  <projet id="2">
    <titre>Poulailler</titre>
    <idBranche>1</idBranche>
    <synopsis>Ce projet simule un poulailler</synopsis>
    <ajouteLe>02/06/2009</ajouteLe>
    <responsables>
      <responsable>Eric Lefrançois</responsable>
    </responsables>
    <auteurs>
      <auteur>Raphaël Tripet</auteur>
      <auteur> Grégory Moinat</auteur>
    </auteurs>
    <motsCle>
      <motCle>WEB</motCle>
      <motCle> Ruby on rails</motCle>
      <motCle> Poules</motCle>
      <motCle> Paysan</motCle>
      <motCle>MySQL</motCle>
    </motsCle>
    <nomArchive>Titre.jpg</nomArchive>
  </projet>
</projets>
